### ISSUE TITLE
[BUG] No longer mutes with Zoom

### ISSUE THREAD

**Issue by aidenybai** [DanielGilbert/dgMicMute#6]
**Describe the bug**
I've been using this application for a couple months now, and it has been working great! However, dgMicMute no longer works with Zoom 5.5.2

**To Reproduce**
1. Open Zoom and make sure you are on v5.5.2 or latest
2. Join any meeting
3. Mute on Zoom
4. Mute on dgMicMute
5. Unmute on Zoom
6. dgMicMute displays an unmuted icon and becomes unmuted

**Expected behavior**
dgMicMute should not show an unmuted icon and become unmuted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version & Build: Version 20H2 (Build 19042.804)

**Comment by DanielGilbert** [comment]
Thanks a lot for your feedback! I'm not a vivid zoom user, so I'd need to setup a test environment first. Does this behaviour also show up if you tick the "Keep State" checkbox in dgMicMute?

**Comment by aidenybai** [comment]
When I leave it off, it kind of switches back and forth. I've seen inconsistent results lately so I can't give a definitive answer

**Comment by aidenybai** [comment]
Reinstalled and it automatically fixed itself. Closing

**Comment by DanielGilbert** [comment]
> Reinstalled and it automatically fixed itself. Closing

Self-fixing bugs. These are my most favourite! 😍

Just kidding. Of course I prefer the reproducible ones. In case this issue should appear again, feel free to re-open this issue.
